# Configurazione dell'applicazione Spring Boot
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/phytosend_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Esegue data.sql dopo che Hibernate ha creato le tabelle
spring.jpa.defer-datasource-initialization=true

# Frontend Configuration
app.frontend.url=http://localhost:5173

# Perenual API Key
perenual.api.key=${PERENUAL_API_KEY}
perenual.api.url=https://perenual.com/api/species-list

# JWT Configuration
jwt.secret=phytosendSecretKeyWithAtLeast256BitsForSecurityRequiresBase64Ideally
jwt.expiration=86400000

