# Configurazione dell'applicazione Spring Boot
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/phytosend_db
spring.datasource.username=phytouser
spring.datasource.password=phytopassword
spring.jpa.hibernate.ddl-auto=update

# Esegue data.sql dopo che Hibernate ha creato le tabelle
spring.jpa.defer-datasource-initialization=true

# Perenual API Key
perenual.api.key=sk-kmrn69aef8951637f15315
perenual.api.url=https://perenual.com/api/species-list
