name: phytosend

services:
  # DATABASE
  db:
    image: postgres:17.6
    container_name: phytosend-db
    restart: always
    environment:
      POSTGRES_DB: phytosend_db
      POSTGRES_USER: phytouser
      POSTGRES_PASSWORD: phytopassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - phytosend-network

  # BACKEND
  backend:
    build:
      context: ..
      dockerfile: DockerFile
    container_name: phytosend-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ../uploads:/app/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phytosend_db
      - SPRING_DATASOURCE_USERNAME=phytouser
      - SPRING_DATASOURCE_PASSWORD=phytopassword
    depends_on:
      - db
    networks:
      - phytosend-network

  # FRONTEND
  frontend:
    build:
      context: ../../frontend
      dockerfile: DockerFile
    container_name: phytosend-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - phytosend-network

volumes:
  db_data:

networks:
  phytosend-network:
    driver: bridge
